// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOunN-XLMwrqHzO0ysD9G3DZLsEpf7Pqg',
    appId: '1:421097357772:web:d6cadc4036eebac80cdd69',
    messagingSenderId: '421097357772',
    projectId: 'eateasy-f20d6',
    authDomain: 'eateasy-f20d6.firebaseapp.com',
    storageBucket: 'eateasy-f20d6.appspot.com',
    measurementId: 'G-0WVGK621SR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiLFBRlxYMV88onyigph9zoG-FGH4Ec3Y',
    appId: '1:421097357772:android:dc253ed40366d5dc0cdd69',
    messagingSenderId: '421097357772',
    projectId: 'eateasy-f20d6',
    storageBucket: 'eateasy-f20d6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIeGOEfgDGAme209wlvtC7MWu3tad6yTw',
    appId: '1:421097357772:ios:f8b3b7bcfd57f4af0cdd69',
    messagingSenderId: '421097357772',
    projectId: 'eateasy-f20d6',
    storageBucket: 'eateasy-f20d6.appspot.com',
    iosClientId: '421097357772-q7pni1oamo6t7cqdvc22tc64lhve26lm.apps.googleusercontent.com',
    iosBundleId: 'com.prerak.eatEasy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIeGOEfgDGAme209wlvtC7MWu3tad6yTw',
    appId: '1:421097357772:ios:cded1eefff4b60500cdd69',
    messagingSenderId: '421097357772',
    projectId: 'eateasy-f20d6',
    storageBucket: 'eateasy-f20d6.appspot.com',
    iosClientId: '421097357772-el2j9g3kbe6956d51ovqlplu8kjfga9u.apps.googleusercontent.com',
    iosBundleId: 'com.prerak.eatEasy.RunnerTests',
  );
}
